# Generated by Django 2.0.5 on 2018-09-11 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email_address', models.EmailField(max_length=200)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('members', models.ManyToManyField(through='swa_app.Membership', to='swa_app.UserAccount')),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='usr_acct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swa_app.UserAccount'),
        ),
        migrations.AddField(
            model_name='membership',
            name='usr_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swa_app.UserRole'),
        ),
    ]
